language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: AXQzymAbbF2+3gfglliSGOPsDkPg4f5URZPsqZ8F6sDaeM5/Joipcat1eamr/KqzVetuTLo0g7cpVDq2ebks6o0/Xh2c+9maFSiu3ZoxLJOp6xWFMURJ73Sh/8gRgkMbKB7DpIrs9rRfCrW79YdUTGQr6pBGH7HG+K2gV4F2ZI8jU4JkULqseH3uwec1d3bvK0C/cxvsDGXeEtOw2rY/NydKumxW1naZGK9a5XopyF1B75PKkHB0D7ddE2d/finHU/QyM1xhhhmci/kP3eE7bAxIbc/6uwbq3J1YPITGdx3TKl+uHGowtDmrazCaDIfOJvDB1ofY4F/EL7tOoYWsQjnfKIvGd1kIc7B24PqBI9x/ymPLyt6wPF9rjHT+3isMNo6tm4ExYZrAyTsy0Y504XMmdFoguyU3kHDDkI3OHapRwP9H/v/FvkohuPHwpgsD5c/lb/05bvbIOvceOOyLoY7Lw702kLCJ3FfHr+IMQ/SbNFfhfi0+LCvQuGR9mgiyWEhmWWQ8hIF9VRQhKAKTf6yzpE4vsVekScIA72BSqGeIt9+luDybia+RrBjCr+ElrX5Uurumn4Jg+l4NLyg92HqGoBbutuLX8rSJAIFtFoa3mrKN1Jgh32xhGBPdxK0AQKGnur+ImMv3Bag8F2a2BVzJihZY7w/y1YNA7NYsAek=
  app: leds-zeppelin-web
  on:
    repo: asleao/leds-zeppellin-web
